# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTWindow.ui'
#
# Created: Tue May  3 01:24:18 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.resize(1015, 682)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
    MainWindow.setSizePolicy(sizePolicy)
    MainWindow.setMinimumSize(QtCore.QSize(899, 400))
    MainWindow.setMaximumSize(QtCore.QSize(10000, 10000))
    font = QtGui.QFont()
    font.setPointSize(10)
    MainWindow.setFont(font)
    MainWindow.setMouseTracking(False)
    self.centralwidget = QtGui.QWidget(MainWindow)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
    self.centralwidget.setSizePolicy(sizePolicy)
    self.centralwidget.setMinimumSize(QtCore.QSize(800, 557))
    self.centralwidget.setMaximumSize(QtCore.QSize(10000, 10000))
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
    self.horizontalLayout_3.setSpacing(0)
    self.horizontalLayout_3.setMargin(2)
    self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
    self.tabWidget = QtGui.QTabWidget(self.centralwidget)
    self.tabWidget.setDocumentMode(True)
    self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
    self.ViewPage = QtGui.QWidget()
    self.ViewPage.setObjectName(_fromUtf8("ViewPage"))
    self.verticalLayout_2 = QtGui.QVBoxLayout(self.ViewPage)
    self.verticalLayout_2.setMargin(2)
    self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
    self.splitter_2 = QtGui.QSplitter(self.ViewPage)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
    self.splitter_2.setSizePolicy(sizePolicy)
    self.splitter_2.setMaximumSize(QtCore.QSize(10000, 16777215))
    self.splitter_2.setLineWidth(0)
    self.splitter_2.setOrientation(QtCore.Qt.Vertical)
    self.splitter_2.setHandleWidth(6)
    self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
    self.splitter = QtGui.QSplitter(self.splitter_2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
    self.splitter.setSizePolicy(sizePolicy)
    self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.splitter.setLineWidth(0)
    self.splitter.setOrientation(QtCore.Qt.Horizontal)
    self.splitter.setHandleWidth(7)
    self.splitter.setObjectName(_fromUtf8("splitter"))
    self.tblSheet = QtGui.QTableWidget(self.splitter)
    font = QtGui.QFont()
    font.setPointSize(8)
    self.tblSheet.setFont(font)
    self.tblSheet.setAutoFillBackground(False)
    self.tblSheet.setRowCount(993)
    self.tblSheet.setColumnCount(995)
    self.tblSheet.setObjectName(_fromUtf8("tblSheet"))
    self.tblSheet.setColumnCount(995)
    self.tblSheet.setRowCount(993)
    self.tblSheet.horizontalHeader().setMinimumSectionSize(4)
    self.tblSheet.verticalHeader().setDefaultSectionSize(15)
    self.tblSheet.verticalHeader().setMinimumSectionSize(15)
    self.tabWidget_2 = QtGui.QTabWidget(self.splitter_2)
    self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 200))
    self.tabWidget_2.setMaximumSize(QtCore.QSize(10000, 10000))
    self.tabWidget_2.setSizeIncrement(QtCore.QSize(0, 0))
    self.tabWidget_2.setBaseSize(QtCore.QSize(0, 0))
    self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
    self.tabGraphs = QtGui.QWidget()
    self.tabGraphs.setObjectName(_fromUtf8("tabGraphs"))
    self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabGraphs)
    self.horizontalLayout_4.setMargin(2)
    self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
    self.chartsScrollArea = QtGui.QScrollArea(self.tabGraphs)
    self.chartsScrollArea.setSizeIncrement(QtCore.QSize(10, 10))
    self.chartsScrollArea.setAutoFillBackground(False)
    self.chartsScrollArea.setFrameShape(QtGui.QFrame.NoFrame)
    self.chartsScrollArea.setFrameShadow(QtGui.QFrame.Plain)
    self.chartsScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
    self.chartsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
    self.chartsScrollArea.setWidgetResizable(True)
    self.chartsScrollArea.setObjectName(_fromUtf8("chartsScrollArea"))
    self.scrollAreaWidgetContents = QtGui.QWidget()
    self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 767, 504))
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
    self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
    self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
    self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
    self.verticalLayout_3.setMargin(2)
    self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
    self.chartsFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
    self.chartsFrame.setMinimumSize(QtCore.QSize(0, 500))
    self.chartsFrame.setFrameShape(QtGui.QFrame.NoFrame)
    self.chartsFrame.setFrameShadow(QtGui.QFrame.Plain)
    self.chartsFrame.setObjectName(_fromUtf8("chartsFrame"))
    self.gridLayout = QtGui.QGridLayout(self.chartsFrame)
    self.gridLayout.setMargin(2)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.chartGrid = QtGui.QGridLayout()
    self.chartGrid.setSpacing(1)
    self.chartGrid.setObjectName(_fromUtf8("chartGrid"))
    self.gridLayout.addLayout(self.chartGrid, 0, 0, 1, 1)
    self.verticalLayout_3.addWidget(self.chartsFrame)
    self.chartsScrollArea.setWidget(self.scrollAreaWidgetContents)
    self.horizontalLayout_4.addWidget(self.chartsScrollArea)
    self.tabWidget_2.addTab(self.tabGraphs, _fromUtf8(""))
    self.tab_4 = QtGui.QWidget()
    self.tab_4.setObjectName(_fromUtf8("tab_4"))
    self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
    self.frmNotify = QtGui.QFrame(self.splitter_2)
    self.frmNotify.setEnabled(True)
    self.frmNotify.setMaximumSize(QtCore.QSize(16777215, 70))
    self.frmNotify.setFrameShape(QtGui.QFrame.StyledPanel)
    self.frmNotify.setFrameShadow(QtGui.QFrame.Raised)
    self.frmNotify.setObjectName(_fromUtf8("frmNotify"))
    self.verticalLayout = QtGui.QVBoxLayout(self.frmNotify)
    self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
    self.txtModelHints = QtGui.QLabel(self.frmNotify)
    self.txtModelHints.setText(_fromUtf8(""))
    self.txtModelHints.setScaledContents(False)
    self.txtModelHints.setAlignment(QtCore.Qt.AlignCenter)
    self.txtModelHints.setObjectName(_fromUtf8("txtModelHints"))
    self.verticalLayout.addWidget(self.txtModelHints)
    self.pbModelProgress = QtGui.QProgressBar(self.frmNotify)
    self.pbModelProgress.setProperty(_fromUtf8("value"), 24)
    self.pbModelProgress.setObjectName(_fromUtf8("pbModelProgress"))
    self.verticalLayout.addWidget(self.pbModelProgress)
    self.verticalLayout_2.addWidget(self.splitter_2)
    self.tabWidget.addTab(self.ViewPage, _fromUtf8(""))
    self.CodePage = QtGui.QWidget()
    self.CodePage.setObjectName(_fromUtf8("CodePage"))
    self.horizontalLayout_2 = QtGui.QHBoxLayout(self.CodePage)
    self.horizontalLayout_2.setMargin(2)
    self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
    self.txtCode = Qsci.QsciScintilla(self.CodePage)
    self.txtCode.setToolTip(_fromUtf8(""))
    self.txtCode.setWhatsThis(_fromUtf8(""))
    self.txtCode.setObjectName(_fromUtf8("txtCode"))
    self.horizontalLayout_2.addWidget(self.txtCode)
    self.tabWidget.addTab(self.CodePage, _fromUtf8(""))
    self.horizontalLayout_3.addWidget(self.tabWidget)
    MainWindow.setCentralWidget(self.centralwidget)
    self.menubar = QtGui.QMenuBar(MainWindow)
    self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 22))
    self.menubar.setObjectName(_fromUtf8("menubar"))
    self.menu_File = QtGui.QMenu(self.menubar)
    self.menu_File.setObjectName(_fromUtf8("menu_File"))
    self.menu_View = QtGui.QMenu(self.menubar)
    self.menu_View.setObjectName(_fromUtf8("menu_View"))
    MainWindow.setMenuBar(self.menubar)
    self.statusbar = QtGui.QStatusBar(MainWindow)
    self.statusbar.setObjectName(_fromUtf8("statusbar"))
    MainWindow.setStatusBar(self.statusbar)
    self.toolBar = QtGui.QToolBar(MainWindow)
    self.toolBar.setAcceptDrops(False)
    self.toolBar.setObjectName(_fromUtf8("toolBar"))
    MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
    self.dockWidget = QtGui.QDockWidget(MainWindow)
    self.dockWidget.setMinimumSize(QtCore.QSize(200, 128))
    self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
    self.dockWidgetContents = QtGui.QWidget()
    self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
    self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
    self.horizontalLayout.setMargin(2)
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.tvModelList = QtGui.QTreeView(self.dockWidgetContents)
    self.tvModelList.setObjectName(_fromUtf8("tvModelList"))
    self.horizontalLayout.addWidget(self.tvModelList)
    self.dockWidget.setWidget(self.dockWidgetContents)
    MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
    self.actionTest = QtGui.QAction(MainWindow)
    self.actionTest.setObjectName(_fromUtf8("actionTest"))
    self.actionTest1 = QtGui.QAction(MainWindow)
    self.actionTest1.setObjectName(_fromUtf8("actionTest1"))
    self.actionTest_2 = QtGui.QAction(MainWindow)
    self.actionTest_2.setObjectName(_fromUtf8("actionTest_2"))
    self.actionIIOPJ = QtGui.QAction(MainWindow)
    self.actionIIOPJ.setObjectName(_fromUtf8("actionIIOPJ"))
    self.menu_File.addAction(self.actionTest_2)
    self.menu_View.addAction(self.actionIIOPJ)
    self.menubar.addAction(self.menu_File.menuAction())
    self.menubar.addAction(self.menu_View.menuAction())
    self.toolBar.addAction(self.actionTest)
    self.toolBar.addAction(self.actionTest1)

    self.retranslateUi(MainWindow)
    self.tabWidget.setCurrentIndex(0)
    self.tabWidget_2.setCurrentIndex(0)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyFinModels", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabGraphs), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.ViewPage), QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.CodePage), QtGui.QApplication.translate("MainWindow", "Code", None, QtGui.QApplication.UnicodeUTF8))
    self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
    self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
    self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
    self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
    self.actionTest1.setText(QtGui.QApplication.translate("MainWindow", "Test1", None, QtGui.QApplication.UnicodeUTF8))
    self.actionTest_2.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
    self.actionIIOPJ.setText(QtGui.QApplication.translate("MainWindow", "IIOPJ", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qsci

if __name__ == "__main__":
  import sys
  app = QtGui.QApplication(sys.argv)
  MainWindow = QtGui.QMainWindow()
  ui = Ui_MainWindow()
  ui.setupUi(MainWindow)
  MainWindow.show()
  sys.exit(app.exec_())
